# Development environment override
services:
  php:
    volumes:
      - php_root_home:/root/.ssh:rw
      - ./:/srv/app
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      # - /srv/app/vendor
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

volumes:
  php_root_home:
